The build script for musl and sqlite is reworked to download and build SQLeet instead of the original SQLite. The part that downloads the original sqlite is commened out and can be used if needed.
FossilOrigin-Name: ad7c29b8d2db9fff29562372e31ea91d4d83722c

diff --git a/musl_sqlite/build b/musl_sqlite/build
--- a/musl_sqlite/build
+++ b/musl_sqlite/build
@@ -24,27 +24,40 @@ fi
 if [ -f ./sqlite3.c ]; then
   echo "Using the existing file sqlite3.c ..."
 else
-  if [ ! -f ./sqlite*.zip ] && [ ! -f ./sqlite*.tar.gz ]; then
-    echo "Downloading latest SQLite source archive..."
-    { wget -q -O - https://www.sqlite.org/cgi/src/tarball/sqlite3.tar.gz?r=release | tar -xz 2> /dev/null; } || { echo >&2 "Error: Can't download SQLite sources."; exit 2;}
-    cd ./sqlite3
-    echo "Building the amalgamation sqlite3.c ..."
-    ./configure > /dev/null 2>&1 || { echo >&2 "Error: Can't configure SQLite sources"; exit 4; }
-    make sqlite3.c > /dev/null 2>&1 || { echo >&2 "Error: Can't make sqlite3.c"; exit 4; }
-    cd ..
-    cp ./sqlite3/sqlite3.c ./
-    rm -rf ./sqlite3/ &
-  else
-    if [ -f ./sqlite*.zip ]; then
-      files=( sqlite*.zip )
-      echo "Extracting sqlite from ${files[0]}..."
-      unzip -joq "${files[0]}" *sqlite3.c || { echo >&2 "Error: Broken SQLite source archive."; exit 2; }
-    else 
-      files=( sqlite*.tar.gz )
-      echo "Extracting sqlite from ${files[0]}..."
-      tar --wildcards --strip-components 1 -xzf "${files[0]}" */sqlite3.c || { echo >&2 "Error: Broken SQLite source archive."; exit 2; }
-    fi
-  fi
+
+  echo "Downloading latest SQLeet master branch archive..."
+  { wget -q -O sqleet.zip https://github.com/resilar/sqleet/archive/master.zip; unzip -q sqleet.zip; rm sqleet.zip; } || { echo >&2 "Error: Can't download SQLeet sources."; exit 2;}
+  cd ./sqleet-master
+  echo "Building the amalgamation sqlite3.c ..."
+  script/amalgamate.sh < ./sqleet.c > ../sqlite3.c
+  cd ..
+  rm -rf ./sqleet-master/ &
+
+
+# The following code downloads SQLite sources from the original web site without encryption support!
+#
+#  if [ ! -f ./sqlite*.zip ] && [ ! -f ./sqlite*.tar.gz ]; then
+#    echo "Downloading latest SQLite source archive..."
+#    { wget -q -O - https://www.sqlite.org/cgi/src/tarball/sqlite3.tar.gz?r=release | tar -xz 2> /dev/null; } || { echo >&2 "Error: Can't download SQLite sources."; exit 2;}
+#    cd ./sqlite3
+#    echo "Building the amalgamation sqlite3.c ..."
+#    ./configure > /dev/null 2>&1 || { echo >&2 "Error: Can't configure SQLite sources"; exit 4; }
+#    make sqlite3.c > /dev/null 2>&1 || { echo >&2 "Error: Can't make sqlite3.c"; exit 4; }
+#    cd ..
+#    cp ./sqlite3/sqlite3.c ./
+#    rm -rf ./sqlite3/ &
+#  else
+#    if [ -f ./sqlite*.zip ]; then
+#      files=( sqlite*.zip )
+#      echo "Extracting sqlite from ${files[0]}..."
+#      unzip -joq "${files[0]}" *sqlite3.c || { echo >&2 "Error: Broken SQLite source archive."; exit 2; }
+#    else 
+#      files=( sqlite*.tar.gz )
+#      echo "Extracting sqlite from ${files[0]}..."
+#      tar --wildcards --strip-components 1 -xzf "${files[0]}" */sqlite3.c || { echo >&2 "Error: Broken SQLite source archive."; exit 2; }
+#    fi
+#  fi
+
 fi
 
 
