Improved SQLite/MUSL building script. More semantic html structure of the thread lists.
FossilOrigin-Name: aaf2db454e0a3970803d5ded209d944ab07cdaa6

diff --git a/musl_sqlite/build b/musl_sqlite/build
--- a/musl_sqlite/build
+++ b/musl_sqlite/build
@@ -1,32 +1,67 @@
 #!/bin/sh
 
+# Exit codes:
+#
+# 1: missing source archive. can't download
+# 2: broken source archive.
+# 3: compilation of MUSL failed
+# 4: compilation of SQLite failed
+
+# First, cleanup from previous builds.
+
 rm -rf ./muslsrc/
 rm -rf ./musl/
-rm ./sqlite3.c
-rm ./musl-gcc.specs
+
+# First find sqlite3.c file. As an existing file, existing source archive or download from Internet.
+
+if [ -f ./sqlite3.c ]; then
+  echo "Using the existing file sqlite3.c ..."
+else
+  if [ ! -f ./sqlite*.zip ] && [ ! -f ./sqlite*.tar.gz ]; then
+    echo "Downloading latest SQLite source archive..."
+    { wget -q -O - https://www.sqlite.org/cgi/src/tarball/sqlite3.tar.gz?r=release | tar -xz 2> /dev/null; } || { echo >&2 "Error: Can't download SQLite sources."; exit 2;}
+    cd ./sqlite3
+    echo "Building the amalgamation sqlite3.c ..."
+    ./configure > /dev/null 2>&1 || { echo >&2 "Error: Can't configure SQLite sources"; exit 4; }
+    make sqlite3.c > /dev/null 2>&1 || { echo >&2 "Error: Can't make sqlite3.c"; exit 4; }
+    cd ..
+    cp ./sqlite3/sqlite3.c ./
+    rm -rf ./sqlite3/ &
+  else
+    if [ -f ./sqlite*.zip ]; then
+      files=( sqlite*.zip )
+      echo "Extracting sqlite from ${files[0]}..."
+      unzip -joq "${files[0]}" *sqlite3.c || { echo >&2 "Error: Broken SQLite source archive."; exit 2; }
+    else 
+      files=( sqlite*.tar.gz )
+      echo "Extracting sqlite from ${files[0]}..."
+      tar --wildcards --strip-components 1 -xzf "${files[0]}" */sqlite3.c || { echo >&2 "Error: Broken SQLite source archive."; exit 2; }
+    fi
+  fi
+fi
+
+
+# Second, find the MUSL sources. As an existing archive or download from Internet.
+
+if [ ! -f ./musl*.tar.gz ]; then
+  echo "Downloading MUSL source archive..."
+  { wget https://www.musl-libc.org/releases/musl-latest.tar.gz 2> /dev/null; } || { echo >&2 "Error: missing MUSL sources."; exit 1; }
+fi
+
+echo "Extracting MUSL source code..."
 
 mkdir muslsrc
-tar --wildcards --strip-components 1 -C ./muslsrc/ -xzf ./musl*.tar.gz
-
-# Extract sqlite3.c file;
-# Only one of the following two commands should be uncommented.
-
-# If SQLite is in ZIP file as usual the amalgamation of the official release is. The zip file is smaller,
-# because contains less files.
-#unzip -joq sqlite*.zip */sqlite3.c
-
-# If SQLite is in .tar.gz file as usual the pre-release snapshots are.
-tar --wildcards --strip-components 1 -xzf ./sqlite*.tar.gz */sqlite3.c
+{ tar --wildcards --strip-components 1 -C ./muslsrc/ -xzf ./musl*.tar.gz 2> /dev/null; } || { echo "Error: Broken MUSL source archive."; exit 2; }
 
 cd muslsrc
 
-# Configure and compile MUSL
+# Configure and compile MUSL; 
 
 echo "Compiling MUSL ..."
 
-./configure --prefix=../musl --host=i386 CC="gcc -m32" CFLAGS="-O3 -mpreferred-stack-boundary=2 -march=x86-64" CROSS_COMPILE="/bin/"
-make -j 4 || { echo >&2 "Error: Can't compile MUSL."; exit 1; }
-make -j 4 install || { echo >&2 "Error: Can't install MUSL to the current directory."; exit 1; }
+./configure --prefix=../musl --host=i386 CC="gcc -m32" CFLAGS="-O3 -mpreferred-stack-boundary=2 -march=x86-64" CROSS_COMPILE="/bin/" > /dev/null 2>&1 || { echo >&2 "Error: Can't configure MUSL."; exit 3; }
+make -j 4 > /dev/null 2>&1 || { echo >&2 "Error: Can't compile MUSL."; exit 3; }
+make -j 4 install > /dev/null 2>&1 || { echo >&2 "Error: Can't install MUSL to the current directory."; exit 3; }
 
 cd ..
 rm -rf ./muslsrc/ &
@@ -36,7 +71,7 @@ echo "Create gcc.specs file..."
 # THE BLANK LINES IN THE BELOW TEXT ARE IMPORTANT! 
 # DON'T EDIT IF YOU DON'T KNOW WHAT YOU ARE DOING!
 # IT IS A BLACK GCC MAGIC!
-cat <<EOT > ./musl-gcc.specs
+cat <<EOT > musl/musl-gcc.specs
 *asm:
 --32
 
@@ -79,7 +114,7 @@ EOT
 echo "Compiling SQLite ..."
 
 gcc -m32 -O3 -shared -fno-stack-protector -mpreferred-stack-boundary=2 -march=x86-64    \
-    -specs ./musl-gcc.specs                                                             \
+    -specs musl/musl-gcc.specs                                                          \
     -DSQLITE_DEFAULT_MEMSTATUS=0                                                        \
     -DSQLITE_LIKE_DOESNT_MATCH_BLOBS                                                    \
     -DSQLITE_MAX_EXPR_DEPTH=0                                                           \
@@ -93,15 +128,13 @@ gcc -m32 -O3 -shared -fno-stack-protector -mpreferred-stack-boundary=2 -march=x8
     -DSQLITE_OMIT_AUTHORIZATION                                                         \
     -DSQLITE_THREADSAFE=1                                                               \
     -DSQLITE_ENABLE_STAT4                                                               \
-./sqlite3.c -o ../www/libsqlite3.so							\
-|| { echo >&2 "Error: Can't compile SQLite."; exit 1; }
+./sqlite3.c -o ./libsqlite3.so							        \
+|| { echo >&2 "Error: Can't compile SQLite."; exit 4; }
 
-mv ./musl/lib/libc.so ../www/ld-musl-i386.so
+mv ./musl/lib/libc.so ./ld-musl-i386.so
 rm -rf ./musl/ &
 
-strip ../www/libsqlite3.so
-strip ../www/ld-musl-i386.so
+strip ./libsqlite3.so
+strip ./ld-musl-i386.so
 
-
-rm ./sqlite3.c
-rm ./musl-gcc.specs
+echo "Building process finished successfully."
